services:
  app1:
    build: ./app
    expose:
      - 5000
    restart: always

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - app1
